import Sidebar from "@/components/Sidebar";
import "./globals.css";
import News from "@/components/News";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-neutral-950">
        <div className="flex justify-between max-w-6xl  m-auto ">
          <aside className="hidden sm:inline border-r border-r-stone-700 h-screen pr-3">
            <Sidebar />
          </aside>
          <main>{children}</main>
          <div>
            <News />
          </div>
        </div>
      </body>
    </html>
  );
}
