import Sidebar from "@/components/Sidebar";
import "./globals.css";
import News from "@/components/News";
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Provider>
          <div className="grid grid-cols-[210px_1fr_300px] max-w-[1050px] m-auto">
            <aside className="hidden sm:inline border-r border-r-stone-700 h-screen pr-3">
              <Sidebar />
            </aside>
            <main className="">{children}</main>
            <div className="pl-3 xl:flex-col h-screen border-l border-l-stone-800 hidden lg:flex w-[24rem]">
              <News />
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
